[general]
import = ["~/.config/alacritty/colors.toml"]

live_config_reload = true
ipc_socket = true

[terminal]
shell = "zsh"

[window]
dynamic_padding = true
decorations = "none"
dynamic_title = true

[window.dimensions]
columns = 95
lines = 24

[window.padding]
x = 16
y = 8

[scrolling]
history = 10000
multiplier = 3

[selection]
save_to_clipboard = true

[cursor]
thickness = 0.15

[cursor.style]
shape = "Beam"
blinking = "On"

## FONTS

[font]
normal= { family = "Monaspace Neon NF", style = "Regular"}
size=12

## HINTS
[[hints.enabled]]
command         = "firefox"
hyperlinks      = true
post_processing = true
persist         = false
mouse.enabled   = true
binding         = { key = "U", mods = "Control|Shift" }
regex           = "(ipfs:|ipns:|magnet:|mailto:|gemini://|gopher://|https://|http://|news:|file:|git://|ssh:|ftp://)[^\u0000-\u001F\u007F-\u009F<>\"\\s{-}\\^⟨⟩‘]+"
