[colors.primary]
background = "#1e2124"
foreground = "#d6d4cd"
dim_foreground = "#959283"
bright_foreground = "#f2f1ee"

[colors.cursor]
text = "#1e2124"
cursor = "#d6d4cd"

[colors.selection]
text = "CellForeground"
background = "#393d41"

[colors.normal]
black   = "#1e2124"
red     = "#d97b68"
green   = "#87be60"
yellow  = "#d6c766"
blue    = "#69b3d3"
magenta = "#a693c8"
cyan    = "#60bac7"
white   = "#d6d4cd"

[colors.bright]
black   = "#5b6167"
red     = "#e2988a"
green   = "#a3d087"
yellow  = "#e1d489"
blue    = "#8ec4de"
magenta = "#bcadd6"
cyan    = "#87cbd5"
white   = "#f2f1ee"

[colors.dim]
black   = "#282b2f"
red     = "#b46656"
green   = "#6c9a4f"
yellow  = "#b3a655"
blue    = "#5992ac"
magenta = "#8a79a8"
cyan    = "#4f97a3"
white   = "#a4a29a"
