hot_reload = true
position = "bottom"

[pinned.firefox]
icon = "firefox"
command = "firefox"

[pinned.terminal]
icon = "terminal"
command = "foot"

[pinned.helix]
icon = "helix"
command = "foot hx ~/"
